/** Section labels for the CV output (preview + PDF). Only these translate — form field values are drawn as entered. */
export const CV_LABELS = {
  ar: {
    summary: "الملخص المهني",
    experience: "الخبرات العملية",
    education: "التعليم",
    skills: "المهارات",
    techSkills: "المهارات التقنية:",
    softSkills: "المهارات المهنية:",
    certs: "الشهادات",
    languages: "اللغات",
    fallbackName: "الاسم الكامل",
    achievements: "الإنجازات",
    courses: "الدورات التدريبية",
    gradProject: "مشروع التخرج",
    gpa: "المعدل",
    yearsOfExperience: "سنوات خبرة",
    hoursUnit: "ساعة",
    licenseNumber: "رقم الترخيص/الشهادة",
    summaryAiNote: "✨ سيتم إنشاء ملخصك المهني تلقائياً بالذكاء الاصطناعي بناءً على بياناتك، ويمكنك تعديله لاحقاً في المعاينة.",
    summaryGenerating: "جارٍ إنشاء الملخص المهني بالذكاء الاصطناعي...",
    summaryEditHint: "✏️ يمكنك التعديل مباشرة هنا",
    summaryGenerateError: "تعذّر إنشاء الملخص تلقائياً. يمكنك كتابته بنفسك هنا.",
    summaryPlaceholder: "اكتب ملخصك المهني هنا...",
    showOriginal: "↩️ النص الأصلي",
    hideOriginal: "🔼 إخفاء النص الأصلي",
    useOriginal: "استخدام هذا النص الأصلي",
    itemsGenerateError: "تعذّر تحسين بعض المحتوى تلقائياً بالذكاء الاصطناعي، تم الاحتفاظ بنصك الأصلي ويمكنك تعديله يدوياً.",
    arabicAllowedNote: "✨ يمكنك الكتابة بالعربية حتى في السيرة الإنجليزية — سيقوم الذكاء الاصطناعي بترجمة الملخص والمهام والإنجازات إلى إنجليزية احترافية. الاسم فقط يجب إدخاله بالأحرف الإنجليزية.",
    suggestForMe: "✨ اقترح لي",
    suggestLoading: "جارٍ توليد الاقتراحات...",
    suggestError: "تعذّر توليد اقتراحات تلقائياً. يمكنك الكتابة يدوياً.",
    suggestUse: "استخدام هذا الاقتراح",
    suggestGenericNote: "هذه اقتراحات عامة لبداية احترافية — راجعها وعدّلها لتعكس خبرتك الفعلية قبل الاستخدام.",
    missingSectionTitle: "بعض الأقسام غير مكتملة",
    missingSectionBody: (list) => `لم تقم بتعبئة الأقسام التالية: ${list} — يمكنك المتابعة الآن أو الرجوع لتعبئتها.`,
    missingSectionContinue: "متابعة على أي حال",
    missingSectionBack: "رجوع للتعديل",
  },
  en: {
    summary: "Professional Summary",
    experience: "Work Experience",
    education: "Education",
    skills: "Skills",
    techSkills: "Technical Skills:",
    softSkills: "Professional Skills:",
    certs: "Certifications",
    languages: "Languages",
    fallbackName: "Full Name",
    achievements: "Achievements",
    courses: "Training Courses",
    gradProject: "Graduation Project",
    gpa: "GPA",
    yearsOfExperience: "years experience",
    hoursUnit: "hrs",
    licenseNumber: "License/Certificate No.",
    summaryAiNote: "✨ Your professional summary will be generated automatically by AI based on your data. You can edit it later in the preview.",
    summaryGenerating: "Generating your professional summary with AI...",
    summaryEditHint: "✏️ Click here to edit directly",
    summaryGenerateError: "Couldn't generate the summary automatically. You can write it yourself here.",
    summaryPlaceholder: "Write your professional summary here...",
    showOriginal: "↩️ Original",
    hideOriginal: "🔼 Hide original",
    useOriginal: "Use this original text",
    itemsGenerateError: "Couldn't automatically enhance some content with AI — your original text was kept, and you can still edit it manually.",
    arabicAllowedNote: "✨ You can type in Arabic even for an English CV — AI will translate your summary, tasks, and achievements into professional English. Only the name must be entered in English.",
    suggestForMe: "✨ Suggest for me",
    suggestLoading: "Generating suggestions...",
    suggestError: "Couldn't generate suggestions automatically. You can write it yourself.",
    suggestUse: "Use this suggestion",
    suggestGenericNote: "These are generic professional starting points — review and edit them to reflect your real experience before using them.",
    missingSectionTitle: "Some sections are incomplete",
    missingSectionBody: (list) => `You haven't filled in the following sections: ${list} — you can continue now or go back to complete them.`,
    missingSectionContinue: "Continue anyway",
    missingSectionBack: "Go back and edit",
  },
};
