/** Section labels for the CV output (preview + PDF). Only these translate — form field values are drawn as entered. */
export const CV_LABELS = {
  ar: {
    summary: "الملخص المهني",
    experience: "الخبرات العملية",
    education: "التعليم",
    skills: "المهارات",
    techSkills: "المهارات التقنية:",
    softSkills: "المهارات المهنية:",
    certs: "الشهادات",
    languages: "اللغات",
    fallbackName: "الاسم الكامل",
    projects: "المشاريع",
    achievements: "الإنجازات",
    courses: "الدورات التدريبية",
    gradProject: "مشروع التخرج",
    yearsOfExperience: "سنوات خبرة",
    hoursUnit: "ساعة",
    licenseNumber: "رقم الترخيص/الشهادة",
  },
  en: {
    summary: "Professional Summary",
    experience: "Work Experience",
    education: "Education",
    skills: "Skills",
    techSkills: "Technical Skills:",
    softSkills: "Professional Skills:",
    certs: "Certifications",
    languages: "Languages",
    fallbackName: "Full Name",
    projects: "Projects",
    achievements: "Achievements",
    courses: "Training Courses",
    gradProject: "Graduation Project",
    yearsOfExperience: "years experience",
    hoursUnit: "hrs",
    licenseNumber: "License/Certificate No.",
  },
};
